## Numpy Array operations 

In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic sliciing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3]) 

### Indexing & Slicing on 2d array

In [ ]:
arr_2d = np.array([[1,2,3], 
                   [4,5,6],
                   [7,8,9]
                  ])

print("Specific element", arr_2d[1,2])
print("Perticular Entire row", arr_2d[1])
print("Perticular Entire row, 2nd way", arr_2d[1, :])
print("Perticular Entire Column", arr_2d[:,1])  # Here : is like slicing for rows, selecting the rows we need, here not giving any start or end means all rows


# SLICING both rows and columns
# arr[row_start : row_end-1, col_start : col_end]

print("Perticular Area of matrix", arr_2d[0:2, 0:2])  

### Sorting 1-d and 2-d arrays

In [ ]:
# 1-d array
unsorted = np.array([3,14,1,2,-18, 92])
sorted = np.sort(unsorted)
print(sorted)


# 2-d array
A = np.array([[8, 2], 
              [11, 9], 
              [5, 4]
            ])

print("Sorted 2d array by Column\n", np.sort(A, axis=0))
print("Sorted 2d array  by Row\n", np.sort(A, axis=1))
# default value of axis = 1, therefore, sorting by row happens
print("Default sorting(row wise)\n", np.sort(A))


# Sorting perticular row
A[1] = np.sort(A[1])
print("Final matrix with pertuclar row sorted\n", A)

# Sorting perticular column
A[:, 1] = np.sort(A[:, 1], axis=0)
print("Final matrix with pertuclar Column sorted\n", A)

## Filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)


#### Filtering with mask

In [ ]:
mask = numbers % 2 == 0

print(mask)

### Replacing Filtered values 

In [ ]:
# Replaces all even numbers with -1
numbers[numbers % 2 == 0] = -1 
print(numbers)

## np.where()

In [3]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

where_result = np.where(numbers > 5)
print(where_result, type(where_result))
print(type(where_result[0]))

print(numbers[where_result])


(array([5, 6, 7, 8, 9]),) <class 'tuple'>
<class 'numpy.ndarray'>
[ 6  7  8  9 10]


In [ ]:
arr = np.array([[1, 6, 9, 2, 10],
                [8, 3, 11, 14, 3]])

print(np.where(arr > 5))

## merging multiple arrays
<i>np.concatenate((arr1,arr2,arr3...))</i> takes a tuple of all the arrays to be concatenated

In [31]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.array([9,10,11,12])
print(np.concatenate((arr1,arr2,arr3)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Addition compatibility check

In [32]:
a = np.array([1, 2, 3])
b = np.array([4,5,6])

print("Compatibility check ", a.shape == b.shape)


Compatibility check  True


# Adding and removing rows/columns

In [37]:
org = np.array([[1,2,3], [4,5,6]])
new_row = np.array([7,8,9])
# New row
with_new_row = np.vstack((org, new_row))

print(org)
print(with_new_row)

new_col = np.array([-1,-1,-1])
print(np.hstack((org, new_col)))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)