In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Practise with real data

In [ ]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("---- SALES ANALYSIS----")

print("\n Sales data shape",sales_data.shape)

print("Data of first three restaurents\n", sales_data[:3, :])


#### Total revenue per year from all restaurents

In [ ]:
# Correct method
revenue_per_year = np.sum(sales_data[:, 1:], axis = 0)    # we sliced into a new matrix to ignore the first column

print(revenue_per_year)


#### Total revenue from each restaurent

In [ ]:
# Correct method
total_rev_rest = np.sum(sales_data[:, 1:], axis = 1)

print(total_rev_rest)

#### Minimum sales per restaurent

In [ ]:
print(np.min(sales_data[:, 1:], axis = 1))

#### Maximum Sales per year

In [ ]:
print(np.max(sales_data[:, 1:], axis=0))

#### Average Sales per restaurant

In [ ]:
print(np.mean(sales_data[:, 1:], axis=1))

#### Getting average sale per month in each year

In [69]:
# Using BROADCASTING scaler division here
print(sales_data[:, 1:]/12)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]


#### Cumulative sum for each restaurant

In [45]:
cumsum = np.cumsum(sales_data[:, 1:], axis=1)
print(cumsum)

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


#### Ploting cumulative sum

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(np.mean(cumsum, axis=0))
plt.title("Average cumulative sales accross all restaurants")
plt.xlabel("Years")
plt.ylabel("Sales")
plt.grid(True)
plt.show()


# Element wise Operations btw Arrays

In [ ]:

v1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
v2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])


# ADDITION
print(v1 + v2)  

# SUBTRACTION
print(v1 - v2)  

# MULTIPLICATION
print(v1*v2)

# DIVISION
print(v1/v2)

# POWER
print(v1**v2)

# MODULUS
print(v1 % v2)


# Matrix Operations (Linear Algebra)

In [ ]:
a = np.array([[2, 1],
              [1, 3]])

b = np.array([[4, 2],
              [1, 5]])


# MULTIPLICATION
print(a @ b)
print(np.matmul(a,b))

# DOT PRODUCT
print(np.dot(a,b))

# TRANSPOSE
print(a.T)
print(a.transpose)

# DETERMINANT
print(np.linalg.det(a))

# INVERSE
print(np.linalg.inv(a))

# Eigenvalues & Eigenvectors
print(np.linalg.eig(a))

# Matrix Rank
print(np.linalg.matrix_rank(a))

# Trace (sum of diagonal)
print(np.trace(a))