In [6]:
import numpy as np

# Numpy array basics

## Creating array from List

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1d array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

1d array: [1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## List Vs Numpy array

#### Scaler Multiplication difference

In [8]:
py_list = [1,2,3,4]
print(py_list*2)

np_array = np.array([1,2,3,4])
print(np_array*2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


#### Time consumption difference

In [9]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("List time taken:", time.time()-start)

start = time.time()
np_list = np.arange(10000000)*2
print("Array time taken:", time.time()-start)

List time taken: 0.42018890380859375
Array time taken: 0.028248071670532227


## Creating different arrays from scratch

#### Creates n-d array of all elements zero

In [10]:
## 1-d array with 'n' elements
zero_arr = np.zeros((3))  
print(zero_arr)

## 2-d array with 'n*m' elements
zero_arr = np.zeros((3,4))  
print(zero_arr)

## 3-d array with 'n*m*k' elements
zero_arr = np.zeros((3,4,2))  
print(zero_arr)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


####  Create n-d array of all elements with value 1

In [11]:
ones_arr = np.ones((2,3))  
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Creating n-d array of a constant value

In [12]:
k_arr = np.full((2,3), 7) # ((dimensions tuple), constant)
print(k_arr)

[[7 7 7]
 [7 7 7]]


#### Creating random valued arrays

In [13]:
# random values in the array are between 0 to
rand = np.random.random((2,3))
print(rand)

# Getting single digit random values
rand =(np.random.random((2,3))*10)//1
print(rand)

# Getting double digit random values
rand =(np.random.random((2,3))*100)//1
print(rand)

[[0.05671923 0.6092965  0.43955207]
 [0.08181687 0.29295806 0.49745556]]
[[5. 0. 8.]
 [9. 4. 9.]]
[[17. 11. 25.]
 [85. 57. 68.]]


# Properties of an Array

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]
                ])

print("Shape", type(arr.shape), arr.shape)
print("Dimension", type(arr.ndim), arr.ndim)
print("Size", type(arr.size), arr.size)   # total number of elements
print("Dtype", type(arr.dtype),arr.dtype)



# Array Reshaping 

#### reshape(), flatten(), ravel(), Transpose

In [45]:
arr = np.arange(12)
print("Original array", arr , "\n", "-"*110)

# New shape must have same total number of elements

a = arr.reshape((3,4))
b = arr.reshape((2,2,3))
print(a)
print(b)
print("-"*110)

## Using -1 instead of row or col, making numpy automatically calculate for it

c = arr.reshape(6,-1)      # cols computed = 2
d = arr.reshape(-1, 4)     # rows computed = 3
print(c)
print(d)
print("-"*110)

# Flattening, convertes n-d array to 1-d (returns copy)
flat_1 = a.flatten()
flat_2 = b.flatten()
print(flat_1)
print(flat_2)
print("-"*110)


# Ravel, converts n-d array to 1-d but returns view of actual array
## thus modifying returned array modifies the actual array

rav_1 = a.ravel()
rav_1[0] = 2
print(rav_1, a)
print("-"*110)

# Transpose
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a.T)


Original array [ 0  1  2  3  4  5  6  7  8  9 10 11] 
 --------------------------------------------------------------------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
--------------------------------------------------------------------------------------------------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------------------------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------------------------------------------------------------------------------------
[ 2  1  2  3  4  5  6  7  8  9 10 11] [[ 2  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------------------------------------------------------------------
[[1 4]
 [2 5]
 [3 6]]
